/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_jecelyin_editor_Grep
#define _Included_com_jecelyin_editor_Grep
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_jecelyin_editor_Grep
 * Method:    find
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jecelyin_editor_Grep_find
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
